language: minimal
#before_install:
#  - chmod +x gradlew
#jdk:
#  - openjdk8
install:
  # `awscli` is required for invalidation of CloudFront distributions.
  - pip install --user awscli
#script:
#  - ./tools/gradlew shadowJar
deploy:
  # move everything from this project into the s3 bucket
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID
  #access_key_id: AKIAVAENIR56NNR55NVD
  #secret_access_key:
  #  secure: MJq53jMYEKgZKeL91PHT+TU1SDjz5ek4uuK5u3+9u9GCYegrc4gg72jmdD3BmawJSkSAXsh8BEF2xLS/ZrV9pH0L2NgWHnaI09LKm1zm49/ijAgqQmsPXjO3ZMDVNG0wC2v4WJcubH6DnYUceEhGTEOPN3XmY6ujJ5IKsSG9lsvzLDcQjngdodUGC1MX8XJ7iDB3NeBi8Rg0r15EPfvgwucDzsn2wmIXCW1hzUQ30r7L7b9CyRN2RVXLveVwWhvwni7shSyKok5SifHVfwYmabKOQ43ffJ2lStdIMowIRXWzg7qrYxNuJJIOqZvACt6Tjb9UaU1pXvk/e1EnMaWmYrfaT8mlHv5pzxjWGpD7t9MfbWpJrIeLfCVoST2j4yKPKZKDd0w7KeUwKiPZnylaBZeoRMaE5T5a9dxs4RpSdD/jWZmHnyxGry4dSwblSPy0Ojhd3SudKP3tWceaWze7W7bZC4TMTRNqJUFNyCZ8DgwuJBXWc00gEu+JLMkzZIPPU3wgq/XiHRPmx6OTHkyHZStSGP1c+A7PlxrECtqW8PSKgq7vWN7IxN64Iqnh5VcQBQzf1Tj6XCe3+rph0ye4q7jqmAqeHz0qC11SBAxuNwNGu6IW301hp/xobMeJ6oqvNo+xfZ7ZrCjf/M2/vIJPgMrtvKOH20SZ7hrgwnx+uLg=
  bucket: timstwitterlisteningparty.com
  acl: public_read
  skip_cleanup: true
  region: eu-west-2
  on:
    repo: matbroughty/timstwitterlisteningparty
after_deploy:
  - aws configure set aws_access_key_id $AWS_ACCESS_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ID
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id E3VMVDBEUWOSL5 --paths "/*"
