language: minimal
#before_install:
#  - chmod +x gradlew
#jdk:
#  - openjdk8
install:
  # `awscli` is required for invalidation of CloudFront distributions.
  - pip install --user awscli
#script:
#  - ./tools/gradlew shadowJar bootJar
deploy:
  # move everything from this project into the s3 bucket
  provider: s3
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID
  bucket: timstwitterlisteningparty.com
  acl: public_read
  skip_cleanup: true
  region: eu-west-2
  on:
    repo: matbroughty/timstwitterlisteningparty
after_deploy:
  - aws configure set aws_access_key_id $AWS_ACCESS_ID
  - aws configure set aws_secret_access_key $AWS_SECRET_ID
  # Allow `awscli` to make requests to CloudFront.
  - aws configure set preview.cloudfront true
  # Invalidate every object in the targeted distribution.
  - aws cloudfront create-invalidation --distribution-id E3VMVDBEUWOSL5 --paths "/index.html" "/snippets/*"
