language: minimal
deploy:
  provider: s3
  access_key_id: AKIAVAENIR56NNR55NVD
  secret_access_key: "YOUR AWS SECRET KEY"
  bucket: timstwitterlisteningparty.com
  skip_cleanup: true
  region: eu-west-2
